var fs = require('fs');
var router = require('base-apps-router');

module.exports = {
  paths: {
    'public':   'public',
    'watched':  ['app']
  },

  files: {
    javascripts: {
      joinTo: {
        'js/app.js':  /^app/,
        'js/vendor.js':  /^(?!app)/
      }
    },
    stylesheets: {
      joinTo: '/css/app.css'
    }
  },

  plugins: {
    babel: {
      presets: ['es2015']
    },
    eslint: {
      // do not run against autogenerated config-routes.js file
      pattern: /^(app)\/(?!config).*\.js?$/
    },
    htmlPages: {
      forceRemoveFrontMatter: true
    },
    postcss: {
      processors: [
        require('autoprefixer')(['> 1%', 'last 2 versions', 'ie >= 10', 'iOS >= 7', 'Safari >= 7', 'Opera >= 25'])
      ]
    }
  },

  hooks: {
    preCompile: (done) => {
      router({
        src: 'app/**/*.html',
        path: 'app/config/config-routes.js',
        root: 'app',
        library: 'node',
        overwrite: true
      }).then(done);
    }
  }
};
